"use client";
import { useState, useEffect } from 'react';
import { Coffee, Citrus, Martini, Search, Sparkles } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
const drinks = [
 {name:'Midnight cold brew',category:'Coffee',price:180,note:'Slow brewed. Smooth finish.',ingredients:'Cold-brew coffee, filtered water, ice',taste:'Chocolate · caramel · smooth',size:'300 ml',caffeine:'Contains caffeine',tone:'coffee'},
 {name:'Vanilla cloud',category:'Coffee',price:240,note:'Espresso meets a softer side.',ingredients:'Espresso, milk, vanilla syrup, ice',taste:'Creamy · mellow · vanilla',size:'350 ml',caffeine:'Contains milk and caffeine',tone:'coffee'},
 {name:'Citrus sunrise',category:'Juice',price:200,note:'A brighter kind of morning.',ingredients:'Orange, pineapple, lime',taste:'Bright · tangy · tropical',size:'350 ml',caffeine:'Caffeine-free',tone:'juice'},
 {name:'Green rhythm',category:'Juice',price:220,note:'Fresh, crisp, quietly bold.',ingredients:'Green apple, cucumber, spinach, lemon',taste:'Fresh · crisp · citrus',size:'350 ml',caffeine:'Caffeine-free',tone:'juice'},
 {name:'Berry afterglow',category:'Mocktails',price:260,note:'A little sparkle after dark.',ingredients:'Berry purée, lime, sparkling water, mint',taste:'Berry · sparkling · tart',size:'350 ml',caffeine:'Alcohol-free and caffeine-free',tone:'berry'},
 {name:'Ginger fizz',category:'Mocktails',price:240,note:'Sharp ginger. Clean citrus.',ingredients:'Ginger syrup, fresh lime, soda water',taste:'Zesty · spicy · sparkling',size:'350 ml',caffeine:'Alcohol-free and caffeine-free',tone:'berry'}
];
type Drink = typeof drinks[number];
export default function Home(){const [category,setCategory]=useState('All drinks');const [query,setQuery]=useState('');const [selected,setSelected]=useState<Drink|null>(null);useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(ctx.registerTool({name:'filter_drinks',description:'Filter the visible SIP menu by category and search text.',inputSchema:{type:'object',properties:{category:{type:'string',enum:['All drinks','Coffee','Juice','Mocktails']},query:{type:'string'}},additionalProperties:false},execute:(input:unknown)=>{const v=input as {category?:string;query?:string};if(!v||typeof v!=='object'||(v.category!==undefined&&!['All drinks','Coffee','Juice','Mocktails'].includes(v.category))||(v.query!==undefined&&typeof v.query!=='string'))throw new Error('Invalid menu filter');const c=v.category??'All drinks',q=v.query??'';setCategory(c);setQuery(q);return {category:c,query:q,drinks:drinks.filter(d=>(c==='All drinks'||d.category===c)&&(d.name+' '+d.ingredients).toLowerCase().includes(q.toLowerCase()))};}}, {signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[]);const shown=drinks.filter(d=>(category==='All drinks'||d.category===category)&&(d.name+' '+d.ingredients).toLowerCase().includes(query.toLowerCase()));return <>
<header className="site-header"><a href="#" className="brand" aria-label="SIP home">sip<span>®</span></a><nav aria-label="Main navigation"><a href="#menu">The menu</a><a href="#philosophy">Our taste</a></nav><span className="header-note">COFFEE · JUICE · MOCKTAILS</span></header>
<main><section className="hero"><div className="hero-copy"><p className="eyebrow">A TASTE FOR THE UNEXPECTED</p><h1>Good drinks.<br/>Great <em>moments.</em></h1><p className="intro">From your first coffee to your last sparkling sip. Find something that fits your mood.</p><a className="button" href="#menu">Discover the menu</a><span className="hero-caption">BOLD FLAVORS. NO ORDINARY SIPS.</span></div><div className="hero-image"><img src="/drinks.jpg" alt="Iced coffee, berry mocktail and citrus juice in glasses on a dark background"/><div className="image-caption"><span>THE SIP COLLECTION</span><span>01 / 03</span></div></div></section>
<div className="ticker" aria-hidden="true"><span>BREWED SLOW</span><i>✳</i><span>SQUEEZED FRESH</span><i>✳</i><span>MIXED WITH INTENTION</span><i>✳</i><span>SIP SOMETHING GOOD</span></div>
<section className="menu" id="menu"><div className="menu-heading"><div><p className="eyebrow">FIND YOUR FLAVOR</p><h2>What’s your <em>mood?</em></h2></div><p>Rich & roasted. Bright & fresh.<br/>Or something with a little sparkle.</p></div><div className="menu-controls"><Tabs value={category} onValueChange={setCategory}><TabsList className="category-tabs">{['All drinks','Coffee','Juice','Mocktails'].map(c=><TabsTrigger className="category-tab" value={c} key={c}>{c}</TabsTrigger>)}</TabsList></Tabs><label className="search"><Search size={18}/><input aria-label="Search drinks or ingredients" placeholder="Find a flavor…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><p className="result-count" role="status">{shown.length} drinks · Prices in ETB</p><div className="drink-grid">{shown.map((d,i)=><button className={'drink-card '+d.tone} key={d.name} onClick={()=>setSelected(d)}><div className="card-top"><span>{d.category}</span>{d.category==='Coffee'?<Coffee size={22}/>:d.category==='Juice'?<Citrus size={22}/>:<Martini size={22}/>}</div><span className="card-number">0{drinks.indexOf(d)+1}</span><h3>{d.name}</h3><p>{d.note}</p><div className="card-bottom"><span>{d.price}<small> ETB</small></span><span className="details-label">Explore drink <span>+</span></span></div></button>)}</div>{!shown.length&&<div className="empty"><h3>No drinks match that flavor.</h3><button className="button" onClick={()=>{setQuery('');setCategory('All drinks')}}>Show all drinks</button></div>}</section>
<section className="philosophy" id="philosophy"><div className="philosophy-symbol"><Sparkles size={60}/></div><div><p className="eyebrow">LESS COMPLICATED. MORE CHARACTER.</p><h2>Every ingredient<br/>has a <em>reason.</em></h2></div><p>Good coffee needs time. Fresh juice needs balance. A memorable mocktail needs a little imagination. Our collection brings all three together, one considered sip at a time.</p></section><footer><a className="brand" href="#">sip<span>®</span></a><p>A drink for every kind of moment.</p><a href="#menu">Explore the collection</a><span>© {new Date().getFullYear()} SIP</span></footer></main>
<Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="drink-dialog">{selected&&<><p className="eyebrow">{selected.category} / THE SIP COLLECTION</p><DialogTitle className="dialog-title">{selected.name}</DialogTitle><DialogDescription className="dialog-note">{selected.note}</DialogDescription><div className="taste">{selected.taste}</div><dl><div><dt>Ingredients</dt><dd>{selected.ingredients}</dd></div><div><dt>Serving</dt><dd>{selected.size}</dd></div><div><dt>Good to know</dt><dd>{selected.caffeine}</dd></div></dl><div className="dialog-price">{selected.price} <span>ETB</span></div></>}</DialogContent></Dialog>
</>}
